#
# !!!
# THIS IS INTENDED FOR DEVELOPMENT ONLY.
# This is not secure and should not be exposed to the internet.
# !!!
#

version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: micro_postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_USER=micro
      - POSTGRES_PASSWORD=youshallnotpass
      - POSTGRES_DB=micro
  minio:
    image: minio/minio
    container_name: micro_minio
    restart: unless-stopped
    command: server /data
    ports:
      - 127.0.0.1:9000:9000
    environment:
      - MINIO_ACCESS_KEY=micro
      - MINIO_SECRET_KEY=youshallnotpass
